export const initialValue = {
  photo: null,
  photo_name: '',
  full_name: '',
  school_name: '',
  address: '',
  mobile_1: '',
  mobile_2: '',
  grno: '',
  standard: '',
  division: '',
  blood_group: '',
  date_of_birth: '',
  house: '',
  fathername: '',
  fathermobile: '',
  mothername: '',
  mothermobile: '',
};
